### ISSUE TITLE
Feedback of Milestone 2 

### ISSUE THREAD

**Issue by Doooooris** [UBC-MDS/SklearncomPYre#37]
- Usage needs to indicates how to use the package and give example code. Only installation instruction are provided.

**Comment by Doooooris** [comment]
- The package can be installed successfully, but unable to import when I use "from SklearncomPYre.comparison_viz import comparison_viz"

**Comment by talhaadnan100** [comment]
Hi @Doooooris ,

We appreciate you taking the time over the weekend to provide us important feedback regarding our package.

It is very important to us that you get the opportunity to use our package since we put a lot of effort into our functions and tests, even if the `readme` did not adequately document the usage steps.

We have addressed the very minor mishap of case-sensitivity (i.e. `SklearncomPYre` vs `sklearncomPYre`) in the package naming in `setup` and `init` files. We acknowledge that the expectation was to have such little tweaks ironed out ahead of submission but as in real life, some bugs inevitably creep in, and in our case a little upper/lower case inconsistency costed us gravely.

Please give our package another try and we are confident that everything should work as intended as per usage documentation in the `readme`.

We realize that our milestone 2 submission is not perfect, but nonetheless we accomplished the major expectations of the milestone in terms of functions and test coverage.

Please let us know if you have any questions or concerns.

Thank you!
@Birinder1469 @jessimk @talhaadnan100

**Comment by Doooooris** [comment]
Would you guys go to my office hour tomorrow, if you want to discuss the problem in the project

**Comment by talhaadnan100** [comment]
Thank you for meeting with our group and providing clarification.
